/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Alfil;
import Logica.Caballo;
import Logica.Peon;
import Logica.Reina;
import Logica.Rey;
import Logica.Torre;
import Logica.Controlador;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author AndresFWilT
 */
public class Vista extends javax.swing.JFrame {

    private String NombreJ1, NombreJ2, ColorJ1, ColorJ2;
    Controlador C;
    boolean bCancelar;

    public Vista() {
    }

    public void IniciarVentana(String n, String n2, String c1, String c2) {
        this.NombreJ1 = n;
        this.NombreJ2 = n2;
        this.ColorJ1 = c1;
        this.ColorJ2 = c2;
        this.setTitle("Ajedrez - juego");
        this.setSize(800, 665);
        initComponents();
        Controlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        PanelPrincipal = new javax.swing.JPanel();
        PanelTablero = new javax.swing.JPanel();
        PanelInfo = new javax.swing.JPanel();
        lJugador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 208, 157));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTablero.setSize(640,640);
        PanelTablero.setBackground(new java.awt.Color(120, 66, 18));

        javax.swing.GroupLayout PanelTableroLayout = new javax.swing.GroupLayout(PanelTablero);
        PanelTablero.setLayout(PanelTableroLayout);
        PanelTableroLayout.setHorizontalGroup(
            PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        PanelTableroLayout.setVerticalGroup(
            PanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        PanelInfo.setSize(130,640);
        PanelInfo.setBackground(new java.awt.Color(238, 208, 157));

        lJugador.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Boton para cancelar ficha*");

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 170, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Controlador() {
        Controlador C = new Controlador(PanelTablero, PanelInfo, NombreJ1, NombreJ2, ColorJ1, ColorJ2);
        C.crearTablero();
        C.addListeners();
    }

    public void Avisos(int Aviso) {
        // declaración de switch
        switch (Aviso) {
            case 1:
                JOptionPane.showMessageDialog(getContentPane(), "Seleccione una ficha suya", "Error", JOptionPane.ERROR_MESSAGE);
                break; // break es opcional
            case 2:
                JOptionPane.showMessageDialog(getContentPane(), "Su ficha actual no puede mover", "Error", JOptionPane.ERROR_MESSAGE);
                break; // break es opcional
            case 3:
                JOptionPane.showMessageDialog(getContentPane(), "Peon acaba de coronar", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
                break; // break es opcional
            case 4:
                JOptionPane.showMessageDialog(getContentPane(), "¡Check!", "ATENCION", JOptionPane.ERROR_MESSAGE);
                break; // break es opcional    
            case 5:
                JOptionPane.showMessageDialog(getContentPane(), "¡CheckMate!", "ATENCION", JOptionPane.ERROR_MESSAGE);
                break; // break es opcional        
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lJugador;
    // End of variables declaration//GEN-END:variables

}
